# Generated by Django 5.0.6 on 2025-05-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centro", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Contenedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenedorId", models.CharField(max_length=100)),
                ("tipo_contenedor", models.CharField(max_length=50)),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                ("capacidad", models.IntegerField()),
                ("unidades", models.CharField(max_length=100)),
                ("fecha_instalacion", models.DateField()),
                ("historico_capacidades", models.JSONField(blank=True, default=list)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contenedores",
                        to="contenedores.centro",
                    ),
                ),
            ],
        ),
    ]
